version: 2

multi-ecosystem-groups:
  all:
    schedule:
      interval: 'monthly'

updates:
  - package-ecosystem: 'maven'
    directories:
      - '**/*'
    patterns: ['*']
    multi-ecosystem-group: 'all'

  - package-ecosystem: 'gradle'
    directories:
      - '**/*'
    patterns: ['*']
    multi-ecosystem-group: 'all'

  - package-ecosystem: 'github-actions'
    directory: '/'
    patterns: ['*']
    multi-ecosystem-group: 'all'
